baseURL = "https://danielms.site"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Daniel Michaels"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "danielms-site"

# Google Analytics
googleAnalytics = "UA-149607103-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Daniel Michaels 🇦🇺"
author = "Daniel Michaels"
copyright = "2018-2021"
description = "I build things and drink coffee."
profilePicture = "extra/cover.jpeg"
keywords = "Software, python"
favicon = "extra/favicon.ico"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["home"]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/daniel-michaels"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/danielmichaels/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/dansult/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:dan@mudmap.io"

## Menu items

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Blog"
weight = 200
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "Retrospectives"
weight = 300
identifier = "retrospectives"
url = "/retrospectives/"

[[menu.main]]
name = "Projects"
weight = 400
identifier = "projects"
url = "/projects/"

[[menu.main]]
name = "About"
weight = 500
identifier = "about"
url = "/about/"

## Taxonomies for Opengraph
[taxonomies]
series = "series"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[permalinks]
blog = "blog/:slug/"
