baseURL = "https://danielms.site/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Daniel Michaels | Developer | Entrepreneur | Veteran"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
buildFuture = true


# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Daniel Michaels 🇦🇺"
author = "Daniel Michaels"
copyright = "2018-2025"
description = "I build things and drink coffee."
profilePicture = "extra/dansult-twitter.jpg"
keywords = "software, python, go, golang, entrepreneur, indie hacker"
favicon = "favicons/"
images = ["extra/danielmichaels.png"]
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["home"]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.umami]
enable = true
websiteID = "e413cf37-7243-475e-bf40-0b9b52f924c0"
scriptURL = "umami.apps.danielms.site"

[params.plausible]
enable = true
domain = "danielms.site"
debug = true
gitstar = false

[parmas.mermaid]
theme = "dark"
align = "center"

# OpenFaaS domain
[params.openfaas]
domain = "https://fn.dansult.space/function"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/daniel-michaels"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/danielmichaels/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/dansult/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:dan@danielms.site"

## Menu items

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Blog"
weight = 200
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "Zet"
weight = 250
identifier = "zet"
url = "/zet/"

[[menu.main]]
name = "Projects"
weight = 300
identifier = "projects"
url = "/projects/"

[[menu.main]]
name = "About"
weight = 400
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Hire"
weight = 500
identifier = "hire"
url = "/hire/"

## Taxonomies for Opengraph
[taxonomies]
series = "series" # lets you link multiple posts such as a 'series'!
category = "categories"
tag = "tags"

[permalinks]
blog = "blog/:slug/"

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'