[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.78.0"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.78.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    
[[redirects]]
from = "https://www.danielmichaels.site/*"
to = "https://www.danielms.site/:splat"
status = 301
force = true
[[redirects]]
from = "https://danielmichaels.site/*"
to = "https://www.danielms.site/:splat"
status = 301
force = true
[[redirects]]
from = "https://confident-visvesvaraya-88fdc6.netlify.com/*"
to = "https://www.danielms.site/:splat"
status = 301
force = true
