name: Zettelkasten

on:
  # run once every hour
  schedule:
    - cron: '0 * * * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.24

      - name: Build fetch-zet
        run: go build -o fetch-zet scripts/fetch-zet.go

      - name: Create zet.json
        env:
          GH_ZET_PAT: ${{ secrets.GH_ZET_PAT }}
        run: ./fetch-zet

      - name: Build top-blogs
        run: go build -o top-blogs scripts/top-blogs.go

      - name: Create top-posts.json
        env:
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}
        run: ./top-blogs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index json files
          commit_options: '--no-verify --signoff'
          file_patterns: "./*.json ./assets/*.json"

