name: Zettelkasten

on:
  # run once every hour
  schedule:
    - cron: '0 * * * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Create zet.json
        env:
          GH_ZET_PAT: ${{ secrets.GH_ZET_PAT }}
        run: go run fetch-zets.go

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update zet.json
          file_patterns: "./zet.json"

